#!/bin/bash

# the main script for managing your blog

current_year=$(date -u +"%Y")

# load the users config file from $HOME
[ -f $HOME/.bl/config ] && source $HOME/.bl/config
# load the local config file
[ -f .site_config ] && source .site_config

# set default blog options .. the syntax below sets the variables
# if not yet set, therefore they can be overidden in the config
# files above
: ${blog_title:-"My blog"}
: ${blog_language:-"en"}
: ${blog_descr:-"My wonderful blog about lots of things."}
: ${blog_keywords:-"blog, news, feed, latest updates"}
: ${blog_categories:-"bash, shell, javascript, css, programming, puppy linux"}
: ${blog_url:-"/mdsh"}  # no trailing slash
: ${blog_author:-"John Doe"}
: ${blog_email:-"foo@bar.com"}
: ${blog_twitter:-"@foobar"}
: ${blog_fonts:-"Ubuntu:400,400i,700|Inconsolata:400,400i,700|Monaco:400,400i,700&subset=latin"}
: ${blog_js_deps:-"cash-dom "}
: ${blog_google_analytics_id:-""}

################################################################################

function setup {
  # blog post pages
  mkdir -p ./posts/$current_year/{01,02,03,04,05,06,07,08,09,10,11,12}/
  # shared site assets
  mkdir -p ./assets/{css,icons,img,js}
  # categories pages
  mkdir -p ./categories/
  # tags pages
  mkdir -p ./tags/
  # set site defaults
  $EDITOR .site_config
  # create the main index page for the site
  ./create_page > index.html
}

function list_related_pages {
  # as above, but pages with matching tags, most tags matched at the top:
  # then list each as
  # <ul class="related-posts">
  #   <li><a href="posts/$post_date/$post_title">$post_title</a></li>
  # </ul>
  :
}

function generate_search_page {
  :  # fuzzy filtering (like my ProjectCMS lang page)
}



function git_add_files {
  # stage the given files.. If no file given, commit all files
  :
}

function git_commit_files {
  # commit the given files.. If no file given, commit all files
  :
}

function git_revert_files {
  # revert the given files ($1)to the given version ($2)
  :
}

function git_push_commit {
  # push the latest commit to GitHub
  :
}

if [ "$1" != "" ];then $1 $2 $3 $4; fi
