#!/bin/bash

# load the users config file from $HOME
[ -f $HOME/.bl/config ] && source $HOME/.bl/config
# load the local config file
[ -f .site_config ] && source .site_config

post_title=''
post_slug=''
post_category=''
post_created=''
post_time_to_read=''
post_url=''
markdown=''
mardown_meta=''
mardown_body=''
body_html=''
output_file=''

# we will write to file if $2 is a file, else to stdout
if [ -f "$2" ];then
  output_file="$2"
fi

################################################################################

# Usage:  set_post_info path/to/post.mdsh
#
#         Used by other functions to set the post info used in various
#         bits of generated HTML.

function set_post_info {
  local md_meta
  # get the meta info from the .mdsh file
  if [ -f "${1//.mdsh/}.mdsh" ];then
    md_meta="$(cat "${1//.mdsh/}.mdsh")"
  elif [ -f "${1//.md/}.mdsh" ];then
    md_meta="$(cat "${1//.md/}.mdsh")"
  else
    return 1
  fi
  # remove post meta data and keep only the body
  md_meta="${md_meta%---*}"
  # set some page specific meta info that will end up in the HTML
  post_title="$(echo "$md_meta"        | grep -m1 '# title'       | cut -f2 -d':' | sed 's/^ *//')"
  post_slug="$(echo "$md_meta"         | grep -m1 '# slug '       | cut -f2 -d':' | sed -e 's/^ *//')"
  post_descr="$(echo "$md_meta"        | grep -m1 '# description' | cut -f2 -d':' | sed 's/^ *//')"
  post_category="$(echo "$md_meta"     | grep -m1 '# category'    | cut -f2 -d':' | sed 's/^ *//' | cut -f1 -d',')"
  post_created="$(echo "$md_meta"      | grep -m1 '# created'     | cut -f2 -d':' | sed 's/^ *//')"
  post_time_to_read="$(echo "$md_meta" | grep -m1 '# time to read'| cut -f2 -d':' | sed 's/^ *//')"
  post_tags="$(echo "$md_meta"         | grep -m1 '# tags'        | cut -f2 -d':' | sed 's/^ *//')"
  post_language="$(echo "$md_meta"     | grep -m1 '# language'    | cut -f2 -d':' | sed 's/^ *//')"
  post_author="$(echo "$md_meta"       | grep -m1 '# author'      | cut -f2 -d':' | sed 's/^ *//')"
  post_twitter="$(echo "$md_meta"      | grep -m1 '# twitter'     | cut -f2 -d':' | sed 's/^ *//')"
  post_js_deps="$(echo "$md_meta"      | grep -m1 '# JS deps'     | cut -f2 -d':' | sed 's/^ *//')"
  # set furll title and url
  [ "$post_title" != "" ] && post_title="$blog_title - $post_title"
  post_url="${blog_url}/posts/$post_created/${post_slug}.html"
}


################################################################################

#
# functions for building HTML pages
#

# create an HTML page
function create_page_html {
  local lang="${blog_language:-en}"
  local site_header="$(print_site_header)"
  local prev_and_next_posts=''
  echo "<!DOCTYPE html>
<!--[if lte IE 6]><html lang=\"$lang\" class=\"preIE7 preIE8 preIE9 preIE11\"><![endif]-->
<!--[if IE 7]><html lang=\"$lang\" class=\"preIE8 preIE9 preIE11\"><![endif]-->
<!--[if IE 8]><html lang=\"$lang\" class=\"preIE9 preIE11\"><![endif]-->
<!--[if IE 9]><html lang=\"$lang\" class=\"preIE11\"><![endif]-->
<!--[if IE 10]><html lang=\"$lang\" class=\"preIE11\"><![endif]-->
<!--[if gte IE 11]><!--><html lang=\"$lang\"><!--<![endif]-->"
  echo "<head>"
  print_site_meta
  print_site_inline_styles
  print_site_stylesheets
  print_site_javascripts
  echo "</head>"
  echo "<body>"
  echo '<div class="main-container">'
  echo '<div class="body-container">'
  echo "$site_header"
  echo '<div id="content" class="post-content">'
  echo -e "$body_html"
  echo "</div>"
  print_post_footer
  echo "</div>"
  print_site_footer
  echo "</div>"
  echo "</body>"
  echo "</html>"
}


function print_site_meta {
  local page_title="$blog_title"
  # set a nice page title
  if [ "$post_title" != "" ];then
    page_title="$post_title"
  fi
  echo '<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta http-equiv="X-DNS-Prefetch-Control" content="on">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>'${page_title}'</title>
<meta name="description" content="'${post_descr:-$blog_descr}'">
<meta name="subject" content="blog, '${blog_categories}'">
<meta name="generator" content="bl" />
<meta name="medium" content="blog">
<meta name="copyright" content="'${post_author:-$blog_author}'">
<meta name="language" content="'${post_language:-$blog_language}'">
<meta name="robots" content="index,follow">
<meta name="revised" content="'$(date)'">
<meta name="topic" content="'${blog_categories}'">
<meta name="owner" content="'${post_author:-$blog_author}'">
<meta name="pagename" content="'${page_title}'">
<meta property="og:title" content="'${page_title}'">
<meta property="og:description" content="'${post_descr:-$blog_descr}'">
<meta property="og:url" content="'${post_url:-$blog_url}'">
<meta property="og:site_name" content="'${page_title}'">
<meta property="og:type" content="website">
<meta property="og:image" content="'${blog_url}'/assets/img/rss.png">
<meta name="twitter:card" content="summary" />
<meta name="twitter:title" content="'${page_title}'" />
<meta name="twitter:site" content="'${post_twitter:-$blog_twitter}'" />
<meta name="twitter:image" content="'${blog_url}'/assets/img/rss.png" />'
  if [ "${blog_google_analytics_id}" != "" ];then
    echo '<meta name="google-analytics" content="'${blog_google_analytics_id}'">'
  fi
  echo '<link rel="author" href="/humans.txt" />
<link rel="canonical" href="'${blog_url}'/">
<link rel="alternate" type="application/rss+xml" title="Subscribe to ${blog_title}" href="'${blog_url}'/feed.rss" />
<link rel="icon" href="'${blog_url}'/favicon.ico" type="image/vnd.microsoft.icon">'
}

function print_site_inline_styles {
  echo '<style>
  body {
    font-family: Ubuntu, serif;
    font-size: 16px;
  }
  pre, code {
    font-family: Inconsolata, Monaco, monospace, serif;
    font-size: 14px;
  }
</style>'
}

function print_site_stylesheets {
  echo '<link rel="stylesheet" href="'${blog_url}'/assets/css/main.css">'
    local filename="$(basename "$output_file" 2>/dev/null)"
    filename="assets/css/${filename//.html/.css}"
  if [ -f "$filename" ];then
    echo '<link rel="stylesheet" href="'${blog_url}'/'"${filename}"'">'
  fi
  echo '<link rel="stylesheet" href="//fonts.googleapis.com/css?family='${blog_fonts}'">'
}

function print_site_javascripts {
  # optional google analytics
  if [ "$blog_google_analytics_id" != '' ];then
    echo '<!-- google analytics -->
<script type="text/javascript" id="google-analytics">
 var _gaq = _gaq || [];
 _gaq.push(["_setAccount", "'${blog_google_analytics_id:-none}'"]);
 _gaq.push(["_trackPageview"]);
 (function(){
  var ga = document.createElement("script"); ga.type = "text/javascript"; ga.async = true;
  ga.src = ("https:" == document.location.protocol ? "https://ssl" : "http://www") + ".google-analytics.com/ga.js";
  var s = document.getElementsByTagName("script")[0]; s.parentNode.insertBefore(ga, s);
 })();
</script>'
  fi
  # get JS deps from unpkg
  local js_deps="$blog_js_deps"
  # if building a post, append the post specific deps
  if [ "$post_js_deps" != "" ];then
    js_deps="$blog__js_deps $post_js_deps"
  fi
  # add JS packages from unpkg.com
  for pkgname in $(echo "$js_deps" | tr ',' ' ')
  do
    echo '<script id="unpkg-'$pkgname'" defer src="//unpkg.com/'$pkgname'" type="text/javascript"></script>'
  done
  # add site-wide app.js, if it exists
  [ -f ./assets/js/app.js ] && echo '<script id="appjs" defer src="assets/js/app.js" type="text/javascript"></script>'
}

function print_site_header {
  echo '<div class="page-header">'
  echo '<h1><a href="'${blog_url}'/index.html">'$blog_title'</a></h1>'
  echo '<a class="off-screen skip-to-content" href="#content">Skip to content</a>'
  echo '<ul>'

  # include index page(s) .. homepage first, then the others
  echo '<li><a href="'${blog_url}'/index.html">home</a></li>'
  index_pages=$(ls -1 *.html)
  for index_page in $(echo "$index_pages" | grep -vE 'index.html|404.html|^*.html')
  do
    index_name="${index_page//.html/}"
    echo '<li><a href="'${blog_url}'/'$index_page'">'$index_name'</a></li>'
  done

  # include individual categories
  #local site_categories="$(cut -f5 -d'|' ./posts.csv | tr ',' '\n' | sort -u)"
  #for category in $site_categories
  #do
  #  echo '<li><a href="'${blog_url}'/categories/'$category'.html">'$category'</a></li>'
  #done

  echo '</ul>'
  echo '</div>'
}

################################################################################

function print_post_header {
  # exit if we are not building a blog post
  [ "$post_slug" = "" ] && return 0

  echo '<div class="post-header">'
  echo '<div class="post-meta">'
  echo '<span class="category"><a href="'${blog_url}'/categories/'"${post_category}"'.html">'"${post_category}"'</a></span>'
  echo '<span class="time-to-read">'"${post_time_to_read}"'</span>'
  echo '<span class="date">'"$post_created"'</span>'
  echo '<span class="author">'"${post_author:-$blog_author}"'</span>'
  echo '<span class="twitter">'"${post_twitter:-$blog_twitter}"'</span>'
  echo '<div class="tags">'
  for tag in ${post_tags//,/ }
  do
    echo '<span><a href="'${blog_url}'/tags/'"${tag}"'.html">'"$tag"'</a></span>'
  done
  echo '</div>'
  echo '</div>'
  echo '</div>'
}

function print_post_footer {
  # exit if we are not building a blog post
  [ "$post_slug" = "" ] && return 0

  echo '<div class="post-footer">'
  echo '<div class="post-meta">'
  echo '<span class="category"><a href="'${blog_url}'/categories/'"${post_category}"'.html">'"${post_category}"'</a></span>'
  echo '<span class="time-to-read">'"${post_time_to_read}"'</span>'
  echo '<span class="date">'"$post_created"'</span>'
  echo '<span class="author">'"${post_author:-$blog_author}"'</span>'
  echo '<span class="twitter">'"${post_twitter:-$blog_twitter}"'</span>'
  echo '<div class="tags">'
  for tag in ${post_tags//,/ }
  do
    echo '<span><a href="'${blog_url}'/tags/'"${tag}"'.html">'"$tag"'</a></span>'
  done
  echo '</div>'
  echo '</div>'
  if [ "$post_slug" != "" ];then
    echo "$(list_prev_and_next_posts "${post_slug}.mdsh")"
  fi
  echo '</div>'
}


function print_site_footer {
  echo '<div class="footer">'
  echo "<p>${blog_footer}</p>"
  echo '</div>'
}

################################################################################

#
# functions for listing site categories and tags
#

function list_categories {
  echo '<ul class="categories">'
  for category in $(cut -f5 -d'|' ./posts.csv | tr ',' '\n' | sort -u)
  do
    echo '<li><a href="'${blog_url}'/categories/'$(./slugify.sh "${category}")'.html">'${category}'</a></li>'
  done
  echo '</ul>'
}

function list_tags {
  echo '<ul class="tags">'
  for tag in $(cut -f6 -d'|' ./posts.csv | tr ',' '\n' | tr ' ' '\n' | sort -u)
  do
    echo '<li><a href="'${blog_url}'/tags/'$(./slugify.sh "${tag}")'.html">'${tag}'</a></li>'
  done
  echo '</ul>'
}

################################################################################

#
# functions for listing posts in various ways
#

function print_post_preview {
  [ ! "$1" ] && return 1

  set_post_info "$1"

  # exit if we are not building a blog post
  [ "$post_slug" = "" ] && return 0

  echo '<div class="post-preview">'
  echo '<h3><a href="'"${post_title}"'"></a></h3> <datetime>'"${post_created}"'</datetime>'
  echo '<ul class="post-meta">'
  echo '<li>'"${post_time_to_read}"'</li>'
  echo '<li>'"${post_created}"'</li>'
  echo '<li>'"${post_author}"'</li>'
  echo '<li>'"${post_twitter}"'</li>'
  echo '<li>'"${post_category}"'</li>'
  echo '</ul>'
  echo '<ul class="tags">'
  for tag in $blog_keywords
  do
    echo '<li><a href="'${blog_url}'/tags/'$(./slugify.sh "${tag}")'.html">'${tag}'</a></li>'
  done
  echo '</ul>'
  echo '<p>'"${post_descr}"'</p>'
  echo '</div>'
}

function list_recent_posts {
  # list relative paths to the 10 most recent posts in ./posts dir
  local recent_posts="$(cut -f1,2 -d'|' ./posts.csv | sort -r | head -18 | tr '|' '/')"
  # local recent_posts="$(find posts/ -type f -name "*.md" -exec stat -c "%y %n" {} + | sort -r | head -10 | cut -f4 -d' ')"
  local post_name
  # then list each one
  echo '<ul class="recent-posts posts">'
  for post in $recent_posts
  do
    post_name="$(grep -m1 "|$(basename $post)|" posts.csv | cut -f3 -d'|')"
    [ "$post_name" = "" ] && post_name=$(basename ${post//.mdsh/})
    echo '<li><a href="'${blog_url}'/posts/'${post//.mdsh/.html}'">'${post_name}'</a></li>'
  done
  echo '</ul>'
}

function list_posts_matching_tag {
  local tag="$1"
  matching_posts="$(grep -lRE "# tags.*$tag[, ]?" posts/*/*/*/*.mdsh | sort -r)"
  echo '<ul class="posts-matching-tag posts">'
  for post in $matching_posts
  do
    post_name="$(grep -m1 "|$(basename $post)|" posts.csv | cut -f3 -d'|')"
    echo -n '<li><a href="'${blog_url}'/'${post//.mdsh/.html}'">'$post_name'</a></li>'
  done
  echo '</ul>'
}

function list_posts_in_category {
  local category="$1"
  local titles="$(grep "|$category|" ./posts.csv | cut -f1,3 -d'|' | sort -r | cut -f2 -d'|')"

  if [ "$titles" != "" ];then
    echo '<ul class="posts-in-category posts">'
    local OLDIFS=$IFS
    IFS="
"
    for title in $titles
    do
      local created="$(grep -m1 "|$title|" ./posts.csv | cut -f1 -d'|')"
      local slug="$(grep -m1 "|$title|" ./posts.csv | cut -f2 -d'|')"
      local title="$(grep -m1 "|$title|" ./posts.csv | cut -f3 -d'|')"
      echo -n '<li><a href="'${blog_url}'/posts/'$created'/'${slug//.mdsh/}'.html">'$title'</a></li>'
    done
    IFS=$OLDIFS
    echo '</ul>'
  fi
}

function list_prev_and_next_posts {
  local current_post="$(grep "|${1//.mdsh/}.mdsh|" ./posts.csv)"
  local prev_current_next_posts="$(grep -A1 -B1 "|${1//.mdsh/}.mdsh|" ./posts.csv | grep -v "$current_post")"
  if [ "$prev_current_next_posts" = "" ];then
    prev_current_next_posts="$(grep -A1 -B1 "|${1//.mdsh/}|" ./posts.csv)"
  fi
  if [ "$prev_current_next_posts" = "" ];then
    return 1
  fi
  local prev_post=$(echo "$prev_current_next_posts" | head -1)
  local next_post=$(echo "$prev_current_next_posts" | tail -1)

  local prev_date="$(echo "$prev_post" | cut -f1 -d'|')"
  local next_date="$(echo "$next_post" | cut -f1 -d'|')"
  local prev_slug="$(echo "$prev_post" | cut -f2 -d'|')"
  local next_slug="$(echo "$next_post" | cut -f2 -d'|')"
  local prev_title="$(echo "$prev_post" | cut -f3 -d'|')"
  local next_title="$(echo "$next_post" | cut -f3 -d'|')"

  echo '<ul class="prev-next-posts">'
  echo '<li class="prev-post">'
  echo '<span>Previous: </span> '
  echo '<a href="../../../'$prev_date'/'${prev_slug//.mdsh/}'.html">'$prev_title'</a>'
  echo '</li>'
  if [ "$next_title" != "$prev_title" ];then
    echo '<li class="next-post">'
    echo '<span>Next:</span> '
    echo '<a href="../../../'$next_date'/'${next_slug//.mdsh/}'.html">'$next_title'</a>'
    echo '</li>'
  fi
  echo '</ul>'
}

################################################################################

#
# begin processing the given file or string
#

body_html=''
markdown=''

# get markdown from file
if [ -f "${1//.mdsh/}.mdsh" ];then
  markdown="$(cat "${1//.mdsh/}.md")"

# get markdown from file
elif [ -f "${1//.md/}.md" ];then
  markdown="$(cat "${1//.md/}.md")"

# get html from string
elif [ "$1" != "" ] && [ "$1" != "-all" ];then
  body_html="$(echo -e "$1")"

# get html list of recent posts
else
  body_html="<h2>Recent posts</h2>
$(list_recent_posts)"
fi

if [ "$1" = "-all" ];then
  body_html="<h2>Recent posts</h2>
$(list_recent_posts)"
fi

# if we have markdown, not html, we need to convert it
if [ "$markdown" != "" ];then

  # set some variables to put into the post HTML
  set_post_info "$1"

  #
  # do some pre-processing of the markdown before converting to html
  #
  echo "$markdown" > /tmp/markdown
  echo -n '' > /tmp/fixed_markdown
  # setting IFS to only \n is needed to preserve code indentation
  OLDIFS=$IFS
  IFS="
"
  # the -er option is needed to preserve newlines in the code blocks
  while read -er line
  do
    # replace ``` with html pre/code tags, cos the markdown parsers break a lot
    if [[ "$line" =~ '```' ]];then
      [ "$in_code_block" = true  ] && in_code_block=false  || in_code_block=true
      [ "$in_code_block" = false ] && line="</code></pre>" || line="<pre><code>"
    fi
    echo -e "$line" >> /tmp/fixed_markdown
  done<<<$(cat /tmp/markdown)
  IFS="$OLDIFS"

  # get the pre-processed markdown, we will convert that to html
  [ -s /tmp/fixed_markdown ] && markdown="$(cat /tmp/fixed_markdown)"
  rm /tmp/markdown /tmp/fixed_markdown &>/dev/null

  #body_html="$(md2html.sh /tmp/markdown)" # uses github API

  # check our HTML is not empty or an error (from GitHub API)
  if [ "$body_html" = "" ] || \
     [ "$(echo "$body_html" | grep 'Problems parsing JSON')" != "" ] || \
     [ "$(echo "$body_html" ] grep 'API rate limit exceeded')" != "" ];then
    # convert the markdown to HTML
    body_html="$(echo -e "$markdown" | ./markdown.pl)" # or markdown.sh
  fi

fi

# if we have a post header, add that to the page too
post_header="$(print_post_header)"
if [ "$post_header" != "" ];then
  body_html="${body_html/<\/h2>/</h2>$post_header}"
fi

#xmessage "$body_html"
if [ -f "$output_file" ];then
  create_page_html > "$output_file"
else
  create_page_html
fi

unset post_title
unset post_slug
unset post_category
unset post_created
unset post_time_to_read
unset post_url
unset markdown
unset mardown_meta
unset mardown_body
unset body_html
unset output_file

################################################################################
