#!/bin/bash

# minifies HTML and CSS files,  requires no arguments

# usage: minify

# The script will then find all html and css files in the
# current dir (recursively) and replace them with minified
# versions

# minify HTML and CSS
echo "Minifying:  HTML and CSS"

html_files="$(find . -type f -name "*.html" | grep -v 'min.html' | sort -r)"
for html_file in $html_files
do
  #echo "Minifying:  $html_file"
  sed ':a;N;$!ba;s/>\s*</></g' $html_file > ${html_file//.html/.minhtml}
  mv ${html_file//.html/.minhtml} ${html_file}
done

css_files="$(find . -type f -name "*.css" | grep -v '.min.css' | sort -r)"
for css_file in $css_files
do
  cat "$css_file" \
    | grep -v '/\*' \
    | tr -d '\n' \
    | sed -e 's/  / /g' \
          -e 's/ {/{/g' \
          -e 's/{ /{/g' \
          -e 's/ }/}/g' \
          -e 's/: /:/g' \
          -e 's/; /;/g' > "${css_file//.css/.mincss}"
  mv ${css_file//.css/.mincss} ${css_file}
done

