#!/bin/bash

# dirs
# blog posts
mkdir -p ./posts/$current_year/{01,02,03,04,05,06,07,08,09,10,11,12}/
# shared site assets
mkdir -p ./assets/{css,icons,img,js}
# authors pages
mkdir -p ./authors/
# categories pages
mkdir -p ./categories/
# tags pages
mkdir -p ./tags/

# colours
yellow="\033[38;5;3m"
nc="\033[0m"

# site defaults
blog_title="mdsh"
blog_language="en"
blog_descr="mdsh - a simple static site generator for modern websites, written in Bash."
blog_keywords="mdsh, static site generator, project page, open source, blog, news, feed"
blog_categories="blog, bash, shell, javascript, css, programming, puppy linux, test, games"
blog_domain="<USERNAME>.github.io"
blog_url="/mdsh" # no trailing slash
blog_author="YOUR NAME"
blog_email="foo@bar.com"
blog_twitter="@foobar"
blog_fonts='Ubuntu:400,400i,700|Inconsolata:400,400i,700|Monaco:400,400i,700&subset=latin,latin-ext'
blog_js_deps="cash-dom jets"
blog_google_analytics_id=""
blog_footer="© ${blog_title} $(date -u +"%Y"). Powered by <a href=\"https://sc0ttj.github.io/mdsh/\">mdsh</a>"

# let user set site info
echo
echo -ne "${yellow}Enter a blog name:${nc}  "
read -e -i "$blog_title" blog_title
echo

echo -ne "${yellow}Enter a blog language (en, de, etc):${nc}  "
read -e -i "$blog_language" blog_language
echo

echo -ne "${yellow}Enter a blog description (~ 80 words):${nc}  "
read -e -i "$blog_descr" blog_descr
echo

echo -ne "${yellow}Enter some blog keywords (comma separated):${nc}  "
read -e -i "$blog_keywords" blog_keywords
echo

echo -ne "${yellow}Enter some blog categories (comma separated):${nc}  "
read -e -i "$blog_categories" blog_categories
echo

echo -ne "${yellow}Enter the blog domain:${nc}  "
read -e -i "$blog_domain" blog_domain
echo

echo -ne "${yellow}Enter the blog url (no trailing slash):${nc}  "
read -e -i "$blog_url" blog_url
echo

echo -ne "${yellow}Enter the blog author (name or username):${nc}  "
read -e -i "$blog_author" blog_author
echo

echo -ne "${yellow}Enter the blog authors email:${nc}  "
read -e -i "$blog_email" blog_email
echo

echo -ne "${yellow}Enter the blog authors twitter handle:${nc}  "
read -e -i "$blog_twitter" blog_twitter
echo

echo -ne "${yellow}Enter the Google fonts to use (blank for none):${nc}  "
read -e -i "$blog_fonts" blog_fonts
echo

echo -ne "${yellow}Enter the JS deps (space separated NPM package names):${nc}  "
read -e -i "$blog_js_deps" blog_js_deps
echo

echo -ne "${yellow}Enter your Google Analytics ID (blank for none):${nc}  "
read -e -i "$blog_google_analytics_id" blog_google_analytics_id


#
# write site info to .site_config
#

echo "##################################################################

# site defaults

blog_title=\"$blog_title\"
blog_language=\"$blog_language\"
blog_descr=\"$blog_descr\"
blog_keywords=\"$blog_keywords\"
blog_categories=\"$blog_categories\"
blog_domain=\"$blog_domain\"
blog_url=\"$blog_url\" # no trailing slash
blog_author=\"$blog_author\"
blog_email=\"$blog_email\"
blog_twitter=\"$blog_twitter\"
blog_fonts='$blog_fonts'
blog_js_deps=\"$blog_js_deps\"
blog_google_analytics_id=\"\"
blog_footer=\"© \${blog_title} \$(date -u +\"%Y\"). Powered by <a href=\"https://sc0ttj.github.io/mdsh/\">mdsh</a>\"

##################################################################

# nicer command-line interface (CLI)

alias create_page=\"\${PWD}/create_page\"
alias create_post=\"\${PWD}/create_post\"
alias create_rss=\"\${PWD}/create_rss\"
alias generate_sitemap=\"\${PWD}/generate_sitemap.sh\"
alias update_pages=\"\${PWD}/update_pages\"
alias publish=\"\${PWD}/publish\"
alias server=\"\${PWD}/server\"
alias setup=\"\${PWD}/setup\"
" > .site_config

echo
echo
echo -e "Success: File ${yellow}.site_config${nc} updated."
