#!/bin/bash

# Update all index pages across the site which list posts, tags and categories
# because a new post may have been added.

# Usage:  update_pages [-all]

# if -all is give, all HTML pages will be re-built, not just the index
# pages (categories, tags, archive, home/recent posts, etc)

# load the local config file
[ -f .site_config ] && source .site_config

# clean up posts.csv (remove any entries that have missing files)
cp posts.csv /tmp/posts.csv

cut -f1-2 -d'|' /tmp/posts.csv \
  | while read line
    do

      # skip comments
      [ "$(echo "$line" | grep "^#")" != "" ] && continue

      mdshfile="${line//|//}"

      if [ ! -f "posts/$mdshfile" ];then
        # the .mdsh file doesnt exist, remove post from posts list
        echo "Removing: posts/$mdshfile"
        grep -v "^$line" posts.csv > /tmp/posts.csv
        mv /tmp/posts.csv posts.csv

      else
        # mdsh file exists
        # so if the .md file doesnt exist, rebuild it

        # if -all, ....         md -> html
        # if -ALL, .... mdsh -> md -> html
        #
        if [ "$1" = "-all" ] || [ "$1" = "-ALL" ];then
          source_file="$mdshfile"
          html_file="${mdshfile//.mdsh/.html}"
          [ "$1" = "-all" ] && source_file="${mdshfile//.mdsh/.md}"
          # update (rebuild) all posts pages
          echo "Updating: posts/$html_file"
          ./create_page "posts/$source_file" "posts/$html_file"
        fi
      fi

    done

echo "Updating: index.html"
. create_page > index.html

# update yearly indexes
for year in $(ls -1 posts)
do
  [ ! -d posts/$year ] && continue
  yearly_posts="<h2>Posts in $year</h2>$(list_posts_in "$year")"
  [ "$yearly_posts" = "" ] && continue
  echo "Updating: posts/$year/index.html"
  touch posts/$year/index.html
  ./create_page "$yearly_posts" posts/$year/index.html

  # update monthly indexes
  for month in $(ls -1 posts/$year)
  do
    [ ! -d posts/$year/$month ] && continue
    monthly_posts="<h2>Posts in $(date -d $year-$month-01 '+%B') $year</h2>$(list_posts_in "$year/$month")"
    [ "$monthly_posts" = "" ] && continue
    echo "Updating: posts/$year/$month/index.html"
    touch posts/$year/$month/index.html
    ./create_page "$monthly_posts" posts/$year/$month/index.html
  done
done


# update 404 page
echo "Updating: 404.html"
./create_page '<h2>Page not found</h2>
<p>Sorry, the page you are looking for could not be found!</p>
<hr>
<p>Please use the menu to find something else.</p>' > 404.html


# update main archive page
all_posts="$(cut -f1,2 -d'|' ./posts.csv | grep -v "^#" | tr '|' '/' | sort -u | sort -r)"
if [ "$all_posts" != "" ];then
  echo "Updating: archive.html"
  all_post_html='<h2>Archive</h2><ul class="archive-posts posts">'
  for post in $all_posts
  do
    post_title="$(grep -m1 "|$(basename $post)|" posts.csv | grep -v "^#" | cut -f3 -d'|')"
    post_date=$(dirname "$post")
    post_date="${post_date//posts\//}"
    post="posts/$post"
    [ ! -f "$post" ] && continue
    all_post_html="${all_post_html}<li><span>${post_date}</span> <a href=\"${blog_url}/${post//.mdsh/.html}\">${post_title}</a></li>"
  done
  all_post_html="${all_post_html}</ul>"
  touch archive.html
  ./create_page "$all_post_html" archive.html
fi


# update authors index page
touch authors/index.html
./create_page "<h2>Authors</h2>\n$(list_authors)" authors/index.html
# update authors pages
[ ! -d ./authors/ ] && mkdir ./authors/
cut -f4 -d'|' ./posts.csv | tr ',' '\n' | grep -v "^$" | sort -u | while read author
do
  file="authors/$(./slugify.sh "$author").html"
  echo "Updating: $file"
  [ ! -f $file ] && touch $file
  ./create_page "<h2>Posts by $author</h2>\n$(list_posts_by_author "$author")" $file
done


# update category pages
category_posts=''
site_categories="$(cut -f5 -d'|' ./posts.csv | tr ',' '\n'| sort -u)"
for category in $site_categories
do
  category_posts="<h2>Category: $category</h2>$(list_posts_in_category "${category}")"
  [ "$category_posts" = "" ] && continue
  echo "Updating: categories/$category.html"
  touch categories/$category.html
  ./create_page "$category_posts" categories/$category.html
done


# update categories index page
echo "Updating: categories.html"
touch categories.html
./create_page "<h2>Categories</h2>\n$(list_categories)" categories.html

# update category pages
category_posts=''
site_categories="$(cut -f5 -d'|' ./posts.csv | tr ',' '\n'| sort -u)"
for category in $site_categories
do
  category_posts="<h2>Category: $category</h2>$(list_posts_in_category "${category}")"
  [ "$category_posts" = "" ] && continue
  echo "Updating: categories/$category.html"
  touch categories/$category.html
  ./create_page "$category_posts" categories/$category.html
done


# update contact page
if [ "$blog_email" != "" ];then
  echo "Updating: contact.html"

  contact_twitter=''
  if [ "$blog_twitter" != "" ];then
    contact_twitter="<p>You can also contact me on Twitter <a href=\"https://twitter.com/$blog_twitter\" target=\"_blank\">$blog_twitter</a>.</p>"
  fi

  #"<form action=\"https://formspree.io/you@email.com\" method=\"post\">"                 # formspree
  #"<form action=\"mailto:${blog_email}\" enctype=\"text/plain\">"                        # mailto
  #"<form method=\"POST\" action=\"https://www.briskforms.com/go/XXXXXXXXXXXXXXXXXX\">"   # briskforms

  ./create_page "<h1>Contact</h1><p>Send me a message, question, some feedback or whatever.</p>
$contact_twitter
<form id=\"contact-form\" class=\"contact-form\" action=\"\" method=\"POST\">
  <input name=\"_gotcha\" type=\"text\" style=\"display: none;\"></input>
  <div class=\"email\">
    <label for=\"email\">Email</label>
    <input id=\"email\" type=\"email\" name=\"_replyto\" placeholder=\"Your email\"></input>
  </div>
  <div class=\"subject\">
    <label for=\"subject\">Subject</label>
    <input id=\"subject\" type=\"text\" name=\"_subject\" placeholder=\"Subject here...\"></input>
  </div>
  <div class=\"message\">
    <label for=\"message\">Message</label>
    <textarea id=\"message\" name=\"message\" placeholder=\"Your Message...\"></textarea>
  </div>
  <button id=\"send\" type=\"submit\">Send</button>
</form>
<script type=\"text/javascript\">
  // build the contact string
  var str = '${blog_email//@/__ __}';
  str = str.replace('__ __', '@');
  // add it to the page
  document.getElementById('contact-form').setAttribute('action', 'https://formspree.io/' + str);
</script>" > contact.html
fi

# update tags index page
echo "Updating: tags.html"
./create_page "<h2>Tags</h2>\n$(list_tags)" tags.html

# update tags pages
site_tags="$(cut -f6 -d'|' ./posts.csv | tr ',' '\n'| sort -u)"
for tag in $site_tags
do
  tagged_posts="<h2>Tag: $tag</h2>$(list_posts_matching_tag "$tag")"
  [ "$tagged_posts" = "" ] && continue
  echo "Updating: tags/$tag.html"
  touch tags/$tag.html
  ./create_page "$tagged_posts" tags/$tag.html
done

echo "Updating: feed.rss"
./create_rss posts/ > feed.rss

exit 0
