#!/bin/bash

[ ! "$1" ] || [ -z "$1" ] && exit 1

. .site_config

# get URL of page - we will generate the breadcrumb from the URL
url="$1"

# start JSON-ld breadcrumb
echo '<script id="breadcrumb-ld" type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": ['

# set vars used in loop below
crumb=''
year=''
month=''
trailing_slash=''
i=1;

# for each item in URL, build ListItem
for item in $(echo "$url" | tr '/' '\n')
do
  text="$item"
  # build proper date strings, for nice titles
  case "$item" in
    # year
    [0-9][0-9][0-9][0-9])
      year=$item; text="Posts from $item"
    ;;
    # month and day
    [0-1][0-9])
      month=$item
      new_date="$(date -d $year-$month-01 '+%B' 2>/dev/null)"
      # if $1=5, we're in the posts days fir, so use previous (monthly) title
      [ "$i" != "5" ] && text="Posts from $new_date $year" || text="$prev_text"
      prev_text="$text"
    ;;
  esac
  # build the path
  crumb="${crumb}/${item}"
  name="${text//.html/}"
  name="${name//-/ }"
  name="${name//_/ }"
  # title case the the name
  string="$name"
  first="$(echo "$string"  | cut -c1 |tr [:lower:] [:upper:])"
  second="$(echo "$string" | cut -c2-)"
  name="$first$second"

  # set some nice title names
  [ "$name" = "Archive" ] && name="Archives"
  [ "$prev_name" = "Authors" ] && name="Author: $name"
  [ "$prev_name" = "Categories" ] && name="Category: $name"
  [ "$prev_name" = "Tags" ] && name="Tag: $name"

  prev_name="$name"

  # print the ListItem
  echo '  {
    "@type": "ListItem",
    "position": '$i',
    "item": {
      "@id": "https://'${blog_domain}${crumb}'",
      "name": "'$blog_title' - '${name}'"
    }
  },'
  i=$(($i + 1))
done

# end JSON-ld
echo ']
}</script>'

