#!/bin/bash

[ ! "$1" ] || [ -z "$1" ] && exit 1

. .site_config

list_items="$1"

#all_posts="$(cut -f1,2 -d'|' ./posts.csv | grep -v "^#" | tr '|' '/' | sed "s/^/posts\//g" | sort -u | sort -r)"

# start JSON-ld itemList
echo '<script id="itemlist-ld" type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "ItemList",
  "itemListElement": ['

# set vars used in loop below
i=1;

# for each item in URL, build ListItem
item_count=$(echo "$list_items"| wc -l)

for item in $list_items
do
  # print the ListItem
  echo -n '  {
    "@type": "ListItem",
    "position": '$i',
    "url": "https://'${blog_domain}${blog_url}/${item//.mdsh/.html}'"
  }'
  i=$(($i + 1))
  [ $i -le $item_count ] && echo ','
done

# end JSON-ld
echo ']
}</script>'

